apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
spec:
  volumeName: logs-pv         
  storageClassName: ""     
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi